### ISSUE TITLE
Usage example given seems to be wrong. Some more Documentation?

### ISSUE THREAD

**Issue by VladParshin** [dkozar/react-data-menu#8]
Hello,
I'm currently learning reactJS, so sorry if my question comes off as odd. I've come across this, and as part of trying to write a website to learn this, I'm having a ton of issues with the Usage example provided.

To me, it seems that there is missing [array] brackets after the first 'items' in this.state parameters that were given. I'm not sure if that is the only problem with the Usage case you provided, but would be glad for some info or clarifications!

I've been looking at the live demo through the web-browser's dev-tools and it seems like a very nifty little module, I just can't figure out how to get it to work for me :(

Great job on writing it though! Seems like a lot of work was put in.

**Comment by dkozar** [comment]
Hi,

I'm not sure what exactly is the concern. Could you link the line in question?

Cheers!

**Comment by VladParshin** [comment]
So below is the code that is provided as an example with that array. This was a few days ago, and I was having issues trying to figure out how it worked, but the example, even in that basic usage case, was spitting tons of errors out for me in WebStorm to do with context or missing items.

I'll try to display where the issues were, but I cannot remember where all of these were, as I went ahead with another menu module for the moment.

```

export class App extends Component {

    constructor(props) {
        super(props);

        this.state = {
            position: {
                x: 100,
                y: 100
            },
            items: _<THIS seems to be missing an square bracket>[_ {
                type: 'label',
                title: 'Menu Popup 1'
            }, '-' _<if the dash is not within a [ ] it gives issues>_ , {
                title: 'Menu item 1-1',
                callback: callback,
                items: [{ // sub-menu
                    title: 'Menu Popup 2'
                }, '-', {
                    title: 'Menu item 2-1',
                    callback: callback,
                    items: [{ // sub-sub-menu
                        title: 'Menu Popup 3'
                    }, '-', {
                        title: 'Menu item 3-1'
                    }]
                }]
            }, {
                title: 'Menu item 1-2'
            }, '-', {
                 type: 'link',
                 title: 'Give me the stars!',
                 url: 'https://github.com/dkozar/react-data-menu/stargazers',
                 target: '_blank'
            }];
        };
    }

    render() {
//        var renderers = {
//            'link': LinkRenderer
//        };

_<I had to remove the link renderer, as it is not part of the included module, nor did I find one on NPM to install that matches that it's also underlined below as I can't strike-through>_
    
        return (
            <Menu items={this.state.items} position={this.state.position} _renderers={renderers}_ />
        );
    }
}

render(<App />, document.body);
```

I know it's an older project, but you might want to pop the example into a test and see if it works.
I was looking into the demo page's source code as well, and it seems to be written and structured a little differently, which threw me off.

**Comment by dkozar** [comment]
Yes, there is an error in the docs - sorry for that and thanks for finding it.

I've written this snipped by hand, in order to condense everything into a 1-pager and I've never actually run it. 

For proper configuration, please see the demo code: https://github.com/dkozar/react-data-menu/blob/7bc93b7967f3540a5c060eef5a48135e2ea9ace4/src/data/items1.js

Yes, the demo is structured differently, with a purpose: [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns).

As for the `LinkRenderer`, it's here: https://github.com/dkozar/react-data-menu/blob/7bc93b7967f3540a5c060eef5a48135e2ea9ace4/src/renderers/LinkRenderer.js

As you already said, this is an old project and I don't actively maintain it.

However, the concepts used in it are still usable (I might say even very advanced, considering the state of similar menu controls). Hopefully, at some point, someone rewrites the project using `TypeScript`.
